/* ⚔ PVPCoreX Hub — Plugin manifest
   Update this file when you add a new plugin build. */
const PLUGINS = [
    {
        id: "pvpcorex",
        name: "PVPCoreX",
        file: "PVPCoreX-1.0.0.jar",
        category: "pvp",
        icon: "⚔️",
        tag: "FLAGSHIP",
        description: "The ultimate all-in-one PvP ecosystem: combat logging, kill streaks, kill effects, duels with ELO, bounties, death chests, supply drops, KOTH and full PvP stats.",
        features: ["CombatX", "KillStreakX", "DuelX", "BountyX", "DeathChestX", "KOTHX"],
        size: "31.2 MB",
        version: "1.0.0",
        paper: "1.21+"
    },
    {
        id: "ultimatevoice",
        name: "UltimateVoice",
        file: "UltimateVoice-1.0.0.jar",
        category: "voice",
        icon: "🎙️",
        tag: "VOICE CHAT",
        description: "Enterprise-grade voice communication plugin with Simple Voice Chat integration. Groups, 1v1 calls, friends, block list, animated premium GUI and database persistence.",
        features: ["Voice Calls", "Groups", "Animated GUI", "SQLite/MySQL"],
        size: "21.9 MB",
        version: "1.0.0",
        paper: "1.21+"
    },
    {
        id: "crowzanticheat",
        name: "CrowzCAnticheat",
        file: "CrowzCAnticheat.jar",
        category: "security",
        icon: "🛡️",
        tag: "ANTICHEAT",
        description: "Custom anticheat engine protecting your server from hackers and cheaters. Lightweight detection with minimal false positives.",
        features: ["Anti-KillAura", "Anti-Fly", "Detection Alerts"],
        size: "0.4 MB",
        version: "1.0.0",
        paper: "1.21+"
    },
    {
        id: "crowzantivpn",
        name: "CrowzAntiVPN",
        file: "CrowzAntiVPN-1.0.0.jar",
        category: "security",
        icon: "🚫",
        tag: "SECURITY",
        description: "Blocks VPN, proxy and bot connections before they reach your server. Keeps your player base safe from alt accounts and ban evaders.",
        features: ["VPN Detection", "Proxy Block", "Alt Protection"],
        size: "0.1 MB",
        version: "1.0.0",
        paper: "1.21+"
    },
    {
        id: "crowzpvp",
        name: "CrowzPVP",
        file: "crowzpvp-1.0.0.jar",
        category: "pvp",
        icon: "🗡️",
        tag: "PVP",
        description: "Streamlined PvP plugin with combat enhancements, kits and arena-style mechanics. Lightweight and performance friendly.",
        features: ["Kits", "Combat Enhancements"],
        size: "0.1 MB",
        version: "1.0.0",
        paper: "1.21+"
    },
    {
        id: "crowzoptimizer",
        name: "CrowzOptimizer",
        file: "CrowzOptimizer-1.0.0.jar",
        category: "utility",
        icon: "⚡",
        tag: "PERFORMANCE",
        description: "Server performance optimizer that trims unused features, reduces lag and improves tick rates without touching gameplay.",
        features: ["Lag Reduction", "Tick Optimizer"],
        size: "0.1 MB",
        version: "1.0.0",
        paper: "1.21+"
    },
    {
        id: "crowzperformance",
        name: "CrowzPerformance",
        file: "crowzperformance-1.0.0.jar",
        category: "utility",
        icon: "🚀",
        tag: "PERFORMANCE",
        description: "Advanced performance toolkit for high-player-count servers. Fine-grained control over mob limits, redstone and entity processing.",
        features: ["Entity Limits", "Redstone Control"],
        size: "0.1 MB",
        version: "1.0.0",
        paper: "1.21+"
    },
    {
        id: "armordurability",
        name: "CrowzArmorDurability HUD",
        file: "crowz-armordurability-hud-1.0.0.jar",
        category: "utility",
        icon: "🛡️",
        tag: "HUD",
        description: "Armor durability heads-up display that shows your armor condition at a glance. Fully customizable colors and positions.",
        features: ["Durability HUD", "Customizable"],
        size: "0.1 MB",
        version: "1.0.0",
        paper: "1.21+"
    },
    {
        id: "enclavejoinandquit",
        name: "EnclaveJoinAndQuit",
        file: "EnclaveJoinAndQuit-1.0.0.jar",
        category: "core",
        icon: "👋",
        tag: "JOIN MESSAGES",
        description: "Premium join/quit messages with custom titles, sounds, particles and per-player first-join messages.",
        features: ["Join/Quit", "Titles", "Sounds"],
        size: "0.1 MB",
        version: "1.0.0",
        paper: "1.21+"
    },
    {
        id: "enclaveshop",
        name: "EnclaveShop",
        file: "EnclaveShop-1.0.0.jar",
        category: "economy",
        icon: "🛒",
        tag: "ECONOMY",
        description: "Player shop system with GUI-based buying and selling. Supports chest shops and command-based shops with Vault integration.",
        features: ["GUI Shop", "Vault Support"],
        size: "0.1 MB",
        version: "1.0.0",
        paper: "1.21+"
    },
    {
        id: "enclavesmp",
        name: "EnclaveSMP",
        file: "EnclaveSMP-1.0.0.jar",
        category: "core",
        icon: "🏠",
        tag: "SMP",
        description: "Complete SMP essentials: homes, spawn, warps, tpa, land protection integration and more. Built for survival multiplayer.",
        features: ["Homes", "Warps", "TPA"],
        size: "0.1 MB",
        version: "1.0.0",
        paper: "1.21+"
    },
    {
        id: "everythingin1",
        name: "EverythingIn1",
        file: "EverythingIn1-1.0.0.jar",
        category: "utility",
        icon: "🧰",
        tag: "ALL-IN-ONE",
        description: "Everything-in-one utility plugin bundling the most requested server features into a single lightweight JAR.",
        features: ["Multi-Feature", "Lightweight"],
        size: "0.2 MB",
        version: "1.0.0",
        paper: "1.21+"
    },
    {
        id: "flowsmp",
        name: "FlowSMP",
        file: "FlowSMP-1.0.0.jar",
        category: "core",
        icon: "🌊",
        tag: "SMP",
        description: "Full SMP suite with economy, player warps, spawn protection, chat formatting and anti-grief protection.",
        features: ["Economy", "Anti-Grief", "Chat"],
        size: "0.2 MB",
        version: "1.0.0",
        paper: "1.21+"
    },
    {
        id: "kaisclearlag",
        name: "KaisClearLag",
        file: "KaisClearLag-1.0.0.jar",
        category: "utility",
        icon: "🧹",
        tag: "LAG FIX",
        description: "Intelligent entity and item cleanup plugin that keeps your server TPS high. Configurable intervals, warnings and exemptions.",
        features: ["Item Cleanup", "Entity Limits"],
        size: "0.1 MB",
        version: "1.0.0",
        paper: "1.21+"
    },
    {
        id: "quitjoin",
        name: "QuitJoin",
        file: "QuitJoin-1.0.0.jar",
        category: "core",
        icon: "🔔",
        tag: "JOIN MESSAGES",
        description: "Lightweight join and quit message plugin with full MiniMessage support and per-player customization.",
        features: ["Join/Quit", "MiniMessage"],
        size: "0.1 MB",
        version: "1.0.0",
        paper: "1.21+"
    },
    {
        id: "staffmoderationplus",
        name: "StaffModerationPlus",
        file: "StaffModerationPlus-1.0.0.jar",
        category: "security",
        icon: "👮",
        tag: "MODERATION",
        description: "Advanced staff moderation suite: vanish, freeze, inventory inspection, chat moderation, and punishment management.",
        features: ["Vanish", "Freeze", "Punishments"],
        size: "0.1 MB",
        version: "1.0.0",
        paper: "1.21+"
    },
    {
        id: "ultimateteam",
        name: "UltimateTeam",
        file: "UltimateTeam-1.0.0.jar",
        category: "core",
        icon: "🤝",
        tag: "TEAMS",
        description: "Team/party management plugin with team chat, friendly fire control, teleportation and team-based PvP support.",
        features: ["Teams", "Team Chat", "Friendly Fire"],
        size: "0.1 MB",
        version: "1.0.0",
        paper: "1.21+"
    },
    {
        id: "v0auth",
        name: "v0Auth",
        file: "v0Auth-1.0.0.jar",
        category: "security",
        icon: "🔐",
        tag: "AUTH",
        description: "Authentication plugin protecting accounts with password login, session support, and brute-force protection.",
        features: ["Password Login", "Sessions"],
        size: "0.1 MB",
        version: "1.0.0",
        paper: "1.21+"
    }
];
